# Generated by Django 4.0.5 on 2022-06-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocrm', '0002_contact_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=50)),
                ('max_tenor', models.IntegerField(default=0)),
                ('max_limit', models.IntegerField(default=0)),
                ('min_price', models.FloatField(default=0)),
                ('base_price', models.FloatField(default=0)),
                ('image_url', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OwnedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('tenor', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocrm.product')),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=30)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('response', models.CharField(max_length=30)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocrm.contact')),
                ('offered_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocrm.product')),
            ],
        ),
    ]
