# Generated by Django 4.0.5 on 2022-06-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocrm', '0004_rename_interactions_interaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedproduct',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocrm.contact'),
        ),
    ]
