# Generated by Django 4.0.5 on 2022-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrm', '0005_ownedproduct_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image_url',
            field=models.CharField(default='https://www.citypng.com/public/uploads/preview/hd-profile-user-round-blue-icon-symbol-transparent-png-11639594354dzabzsbpuv.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
