# Generated by Django 4.0.5 on 2022-06-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocrm', '0006_contact_image_url_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='interaction',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocrm.channel'),
        ),
    ]
