# Generated by Django 4.0.5 on 2022-06-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocrm', '0010_contact_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
